# Generated by Django 5.0.6 on 2024-05-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20)),
                ('in_out', models.CharField(choices=[('input', 'input'), ('output', 'output')], max_length=20)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('location', models.URLField()),
                ('parking_size', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_time', models.DateTimeField(auto_now=True)),
                ('parking_out_time', models.DateTimeField(null=True)),
                ('in_out_cars', models.IntegerField(default=0)),
                ('free_place', models.IntegerField(default=0)),
                ('car_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.car')),
                ('all_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.place')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='parkin_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.place'),
        ),
    ]
